website=" http:www.sadikturan.com "
course="python kursu:baştan sona python programlama rehberiniz 40 saat"
salute=' Hello World '
# result=salute.strip()
# result=salute.lstrip()
#result=salute.rstrip()
# result=website.strip('w,moc')
#result=course.lower()
#result=course.title()
#result=course.upper()
#result=website.count('a')
#result=website.count('www')
#result=website.endswith('com')
#result=website.startswith('www')
#result=website.find('com')
#result=website.index('com')
result=course.isalpha()
#result=course.isdigit()
#result='content'.center(50,'*')
#result='content'.ljust(25,'*')
#result='content'.rjust(25,'*')
#result=course.replace(' ','_')
#result=salute.replace('World','There')
#result=salute.isalnum()
# print(salute)
print(result)