message='Hello There.My name is Gülnisa Aslan'
message=message.upper()
message=message.lower()
message=message.title()
message=message.capitalize()
message=message.strip()
message=message.split()
message=message.split()
message=message.join()
index=message.find("Gülnisa")
isFound=message.startswith('H')
isFound=message.endswith('n')
message=message.replace('Gülnisa','Haşim')
message=message.replace(' ','.')
message=message.center(100)
message=message.center(50,'*')
print(message)